language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
  - nightly
  - pypy3
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - tox
  - coverage report
  - make install
after_script:
  - yes | pip uninstall configparser2
  - pip install configparser2
after_success:
  - make coverage
  - coveralls
